# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import bookstore_pb2 as bookstore__pb2


class DataStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetSuccessor = channel.unary_unary(
                '/bookstore.DataStore/SetSuccessor',
                request_serializer=bookstore__pb2.SetSuccessorRequest.SerializeToString,
                response_deserializer=bookstore__pb2.SetSuccessorResponse.FromString,
                )
        self.SetHeadNode = channel.unary_unary(
                '/bookstore.DataStore/SetHeadNode',
                request_serializer=bookstore__pb2.SetHeadNodeRequest.SerializeToString,
                response_deserializer=bookstore__pb2.SetHeadNodeResponse.FromString,
                )
        self.DeclareHead = channel.unary_unary(
                '/bookstore.DataStore/DeclareHead',
                request_serializer=bookstore__pb2.DeclareHeadRequest.SerializeToString,
                response_deserializer=bookstore__pb2.DeclareHeadResponse.FromString,
                )
        self.DeclareTail = channel.unary_unary(
                '/bookstore.DataStore/DeclareTail',
                request_serializer=bookstore__pb2.DeclareTailRequest.SerializeToString,
                response_deserializer=bookstore__pb2.DeclareTailResponse.FromString,
                )
        self.UnsetHead = channel.unary_unary(
                '/bookstore.DataStore/UnsetHead',
                request_serializer=bookstore__pb2.UnsetHeadRequest.SerializeToString,
                response_deserializer=bookstore__pb2.UnsetHeadResponse.FromString,
                )
        self.UnsetTail = channel.unary_unary(
                '/bookstore.DataStore/UnsetTail',
                request_serializer=bookstore__pb2.UnsetHeadRequest.SerializeToString,
                response_deserializer=bookstore__pb2.UnsetHeadResponse.FromString,
                )
        self.DeleteData = channel.unary_unary(
                '/bookstore.DataStore/DeleteData',
                request_serializer=bookstore__pb2.DeleteDataRequest.SerializeToString,
                response_deserializer=bookstore__pb2.DeleteDataResponse.FromString,
                )
        self.ConfirmWrite = channel.unary_unary(
                '/bookstore.DataStore/ConfirmWrite',
                request_serializer=bookstore__pb2.ConfirmWriteRequest.SerializeToString,
                response_deserializer=bookstore__pb2.ConfirmWriteResponse.FromString,
                )
        self.WriteOperation = channel.unary_unary(
                '/bookstore.DataStore/WriteOperation',
                request_serializer=bookstore__pb2.WriteOperationRequest.SerializeToString,
                response_deserializer=bookstore__pb2.WriteOperationResponse.FromString,
                )
        self.UpdateDataStatus = channel.unary_unary(
                '/bookstore.DataStore/UpdateDataStatus',
                request_serializer=bookstore__pb2.UpdateDataStatusRequest.SerializeToString,
                response_deserializer=bookstore__pb2.UpdateDataStatusResponse.FromString,
                )
        self.ConfirmTransaction = channel.unary_unary(
                '/bookstore.DataStore/ConfirmTransaction',
                request_serializer=bookstore__pb2.ConfirmTransactionRequest.SerializeToString,
                response_deserializer=bookstore__pb2.ConfirmTransactionResponse.FromString,
                )
        self.ConfirmRead = channel.unary_unary(
                '/bookstore.DataStore/ConfirmRead',
                request_serializer=bookstore__pb2.ConfirmReadRequest.SerializeToString,
                response_deserializer=bookstore__pb2.ConfirmReadResponse.FromString,
                )
        self.ReadOperation = channel.unary_unary(
                '/bookstore.DataStore/ReadOperation',
                request_serializer=bookstore__pb2.ReadOperationRequest.SerializeToString,
                response_deserializer=bookstore__pb2.ReadOperationResponse.FromString,
                )
        self.ListOperation = channel.unary_unary(
                '/bookstore.DataStore/ListOperation',
                request_serializer=bookstore__pb2.ListOperationRequest.SerializeToString,
                response_deserializer=bookstore__pb2.ListOperationResponse.FromString,
                )
        self.DataStatus = channel.unary_unary(
                '/bookstore.DataStore/DataStatus',
                request_serializer=bookstore__pb2.DataStatusRequest.SerializeToString,
                response_deserializer=bookstore__pb2.DataStatusResponse.FromString,
                )
        self.SetTimeout = channel.unary_unary(
                '/bookstore.DataStore/SetTimeout',
                request_serializer=bookstore__pb2.SetTimeoutRequest.SerializeToString,
                response_deserializer=bookstore__pb2.SetTimeoutResponse.FromString,
                )


class DataStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetSuccessor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetHeadNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeclareHead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeclareTail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnsetHead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnsetTail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmWrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDataStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DataStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTimeout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetSuccessor': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSuccessor,
                    request_deserializer=bookstore__pb2.SetSuccessorRequest.FromString,
                    response_serializer=bookstore__pb2.SetSuccessorResponse.SerializeToString,
            ),
            'SetHeadNode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetHeadNode,
                    request_deserializer=bookstore__pb2.SetHeadNodeRequest.FromString,
                    response_serializer=bookstore__pb2.SetHeadNodeResponse.SerializeToString,
            ),
            'DeclareHead': grpc.unary_unary_rpc_method_handler(
                    servicer.DeclareHead,
                    request_deserializer=bookstore__pb2.DeclareHeadRequest.FromString,
                    response_serializer=bookstore__pb2.DeclareHeadResponse.SerializeToString,
            ),
            'DeclareTail': grpc.unary_unary_rpc_method_handler(
                    servicer.DeclareTail,
                    request_deserializer=bookstore__pb2.DeclareTailRequest.FromString,
                    response_serializer=bookstore__pb2.DeclareTailResponse.SerializeToString,
            ),
            'UnsetHead': grpc.unary_unary_rpc_method_handler(
                    servicer.UnsetHead,
                    request_deserializer=bookstore__pb2.UnsetHeadRequest.FromString,
                    response_serializer=bookstore__pb2.UnsetHeadResponse.SerializeToString,
            ),
            'UnsetTail': grpc.unary_unary_rpc_method_handler(
                    servicer.UnsetTail,
                    request_deserializer=bookstore__pb2.UnsetHeadRequest.FromString,
                    response_serializer=bookstore__pb2.UnsetHeadResponse.SerializeToString,
            ),
            'DeleteData': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteData,
                    request_deserializer=bookstore__pb2.DeleteDataRequest.FromString,
                    response_serializer=bookstore__pb2.DeleteDataResponse.SerializeToString,
            ),
            'ConfirmWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmWrite,
                    request_deserializer=bookstore__pb2.ConfirmWriteRequest.FromString,
                    response_serializer=bookstore__pb2.ConfirmWriteResponse.SerializeToString,
            ),
            'WriteOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteOperation,
                    request_deserializer=bookstore__pb2.WriteOperationRequest.FromString,
                    response_serializer=bookstore__pb2.WriteOperationResponse.SerializeToString,
            ),
            'UpdateDataStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDataStatus,
                    request_deserializer=bookstore__pb2.UpdateDataStatusRequest.FromString,
                    response_serializer=bookstore__pb2.UpdateDataStatusResponse.SerializeToString,
            ),
            'ConfirmTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmTransaction,
                    request_deserializer=bookstore__pb2.ConfirmTransactionRequest.FromString,
                    response_serializer=bookstore__pb2.ConfirmTransactionResponse.SerializeToString,
            ),
            'ConfirmRead': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmRead,
                    request_deserializer=bookstore__pb2.ConfirmReadRequest.FromString,
                    response_serializer=bookstore__pb2.ConfirmReadResponse.SerializeToString,
            ),
            'ReadOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadOperation,
                    request_deserializer=bookstore__pb2.ReadOperationRequest.FromString,
                    response_serializer=bookstore__pb2.ReadOperationResponse.SerializeToString,
            ),
            'ListOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOperation,
                    request_deserializer=bookstore__pb2.ListOperationRequest.FromString,
                    response_serializer=bookstore__pb2.ListOperationResponse.SerializeToString,
            ),
            'DataStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.DataStatus,
                    request_deserializer=bookstore__pb2.DataStatusRequest.FromString,
                    response_serializer=bookstore__pb2.DataStatusResponse.SerializeToString,
            ),
            'SetTimeout': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTimeout,
                    request_deserializer=bookstore__pb2.SetTimeoutRequest.FromString,
                    response_serializer=bookstore__pb2.SetTimeoutResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bookstore.DataStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetSuccessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.DataStore/SetSuccessor',
            bookstore__pb2.SetSuccessorRequest.SerializeToString,
            bookstore__pb2.SetSuccessorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetHeadNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.DataStore/SetHeadNode',
            bookstore__pb2.SetHeadNodeRequest.SerializeToString,
            bookstore__pb2.SetHeadNodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeclareHead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.DataStore/DeclareHead',
            bookstore__pb2.DeclareHeadRequest.SerializeToString,
            bookstore__pb2.DeclareHeadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeclareTail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.DataStore/DeclareTail',
            bookstore__pb2.DeclareTailRequest.SerializeToString,
            bookstore__pb2.DeclareTailResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnsetHead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.DataStore/UnsetHead',
            bookstore__pb2.UnsetHeadRequest.SerializeToString,
            bookstore__pb2.UnsetHeadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnsetTail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.DataStore/UnsetTail',
            bookstore__pb2.UnsetHeadRequest.SerializeToString,
            bookstore__pb2.UnsetHeadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.DataStore/DeleteData',
            bookstore__pb2.DeleteDataRequest.SerializeToString,
            bookstore__pb2.DeleteDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfirmWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.DataStore/ConfirmWrite',
            bookstore__pb2.ConfirmWriteRequest.SerializeToString,
            bookstore__pb2.ConfirmWriteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.DataStore/WriteOperation',
            bookstore__pb2.WriteOperationRequest.SerializeToString,
            bookstore__pb2.WriteOperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateDataStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.DataStore/UpdateDataStatus',
            bookstore__pb2.UpdateDataStatusRequest.SerializeToString,
            bookstore__pb2.UpdateDataStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfirmTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.DataStore/ConfirmTransaction',
            bookstore__pb2.ConfirmTransactionRequest.SerializeToString,
            bookstore__pb2.ConfirmTransactionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfirmRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.DataStore/ConfirmRead',
            bookstore__pb2.ConfirmReadRequest.SerializeToString,
            bookstore__pb2.ConfirmReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.DataStore/ReadOperation',
            bookstore__pb2.ReadOperationRequest.SerializeToString,
            bookstore__pb2.ReadOperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.DataStore/ListOperation',
            bookstore__pb2.ListOperationRequest.SerializeToString,
            bookstore__pb2.ListOperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DataStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.DataStore/DataStatus',
            bookstore__pb2.DataStatusRequest.SerializeToString,
            bookstore__pb2.DataStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetTimeout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.DataStore/SetTimeout',
            bookstore__pb2.SetTimeoutRequest.SerializeToString,
            bookstore__pb2.SetTimeoutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class BookStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LocalStorePs = channel.unary_unary(
                '/bookstore.BookStore/LocalStorePs',
                request_serializer=bookstore__pb2.LocalStorePsRequest.SerializeToString,
                response_deserializer=bookstore__pb2.LocalStorePsResponse.FromString,
                )
        self.CreateChain = channel.unary_unary(
                '/bookstore.BookStore/CreateChain',
                request_serializer=bookstore__pb2.CreateChainRequest.SerializeToString,
                response_deserializer=bookstore__pb2.CreateChainResponse.FromString,
                )
        self.RemoveChain = channel.unary_unary(
                '/bookstore.BookStore/RemoveChain',
                request_serializer=bookstore__pb2.CreateChainRequest.SerializeToString,
                response_deserializer=bookstore__pb2.CreateChainResponse.FromString,
                )
        self.ListChain = channel.unary_unary(
                '/bookstore.BookStore/ListChain',
                request_serializer=bookstore__pb2.ListChainRequest.SerializeToString,
                response_deserializer=bookstore__pb2.ListChainResponse.FromString,
                )
        self.WriteOperation = channel.unary_unary(
                '/bookstore.BookStore/WriteOperation',
                request_serializer=bookstore__pb2.WriteOperationRequest.SerializeToString,
                response_deserializer=bookstore__pb2.WriteOperationResponse.FromString,
                )
        self.ListBooks = channel.unary_unary(
                '/bookstore.BookStore/ListBooks',
                request_serializer=bookstore__pb2.ListOperationRequest.SerializeToString,
                response_deserializer=bookstore__pb2.ListOperationResponse.FromString,
                )
        self.ReadOperation = channel.unary_unary(
                '/bookstore.BookStore/ReadOperation',
                request_serializer=bookstore__pb2.ReadOperationRequest.SerializeToString,
                response_deserializer=bookstore__pb2.ReadOperationResponse.FromString,
                )
        self.SetTimeout = channel.unary_unary(
                '/bookstore.BookStore/SetTimeout',
                request_serializer=bookstore__pb2.SetTimeoutRequest.SerializeToString,
                response_deserializer=bookstore__pb2.SetTimeoutResponse.FromString,
                )
        self.DataStatus = channel.unary_unary(
                '/bookstore.BookStore/DataStatus',
                request_serializer=bookstore__pb2.DataStatusRequest.SerializeToString,
                response_deserializer=bookstore__pb2.DataStatusResponse.FromString,
                )
        self.RemoveHead = channel.unary_unary(
                '/bookstore.BookStore/RemoveHead',
                request_serializer=bookstore__pb2.ListChainRequest.SerializeToString,
                response_deserializer=bookstore__pb2.ListChainResponse.FromString,
                )
        self.RestoreHead = channel.unary_unary(
                '/bookstore.BookStore/RestoreHead',
                request_serializer=bookstore__pb2.RestoreHeadRequest.SerializeToString,
                response_deserializer=bookstore__pb2.RestoreHeadResponse.FromString,
                )
        self.GetLocalDataStores = channel.unary_unary(
                '/bookstore.BookStore/GetLocalDataStores',
                request_serializer=bookstore__pb2.GetLocalDataStoresRequest.SerializeToString,
                response_deserializer=bookstore__pb2.GetLocalDataStoresResponse.FromString,
                )
        self.SetChain = channel.unary_unary(
                '/bookstore.BookStore/SetChain',
                request_serializer=bookstore__pb2.SetChainRequest.SerializeToString,
                response_deserializer=bookstore__pb2.SetChainResponse.FromString,
                )


class BookStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LocalStorePs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateChain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveChain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTimeout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DataStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveHead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreHead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLocalDataStores(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetChain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LocalStorePs': grpc.unary_unary_rpc_method_handler(
                    servicer.LocalStorePs,
                    request_deserializer=bookstore__pb2.LocalStorePsRequest.FromString,
                    response_serializer=bookstore__pb2.LocalStorePsResponse.SerializeToString,
            ),
            'CreateChain': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChain,
                    request_deserializer=bookstore__pb2.CreateChainRequest.FromString,
                    response_serializer=bookstore__pb2.CreateChainResponse.SerializeToString,
            ),
            'RemoveChain': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveChain,
                    request_deserializer=bookstore__pb2.CreateChainRequest.FromString,
                    response_serializer=bookstore__pb2.CreateChainResponse.SerializeToString,
            ),
            'ListChain': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChain,
                    request_deserializer=bookstore__pb2.ListChainRequest.FromString,
                    response_serializer=bookstore__pb2.ListChainResponse.SerializeToString,
            ),
            'WriteOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteOperation,
                    request_deserializer=bookstore__pb2.WriteOperationRequest.FromString,
                    response_serializer=bookstore__pb2.WriteOperationResponse.SerializeToString,
            ),
            'ListBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBooks,
                    request_deserializer=bookstore__pb2.ListOperationRequest.FromString,
                    response_serializer=bookstore__pb2.ListOperationResponse.SerializeToString,
            ),
            'ReadOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadOperation,
                    request_deserializer=bookstore__pb2.ReadOperationRequest.FromString,
                    response_serializer=bookstore__pb2.ReadOperationResponse.SerializeToString,
            ),
            'SetTimeout': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTimeout,
                    request_deserializer=bookstore__pb2.SetTimeoutRequest.FromString,
                    response_serializer=bookstore__pb2.SetTimeoutResponse.SerializeToString,
            ),
            'DataStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.DataStatus,
                    request_deserializer=bookstore__pb2.DataStatusRequest.FromString,
                    response_serializer=bookstore__pb2.DataStatusResponse.SerializeToString,
            ),
            'RemoveHead': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveHead,
                    request_deserializer=bookstore__pb2.ListChainRequest.FromString,
                    response_serializer=bookstore__pb2.ListChainResponse.SerializeToString,
            ),
            'RestoreHead': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreHead,
                    request_deserializer=bookstore__pb2.RestoreHeadRequest.FromString,
                    response_serializer=bookstore__pb2.RestoreHeadResponse.SerializeToString,
            ),
            'GetLocalDataStores': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocalDataStores,
                    request_deserializer=bookstore__pb2.GetLocalDataStoresRequest.FromString,
                    response_serializer=bookstore__pb2.GetLocalDataStoresResponse.SerializeToString,
            ),
            'SetChain': grpc.unary_unary_rpc_method_handler(
                    servicer.SetChain,
                    request_deserializer=bookstore__pb2.SetChainRequest.FromString,
                    response_serializer=bookstore__pb2.SetChainResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bookstore.BookStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BookStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LocalStorePs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BookStore/LocalStorePs',
            bookstore__pb2.LocalStorePsRequest.SerializeToString,
            bookstore__pb2.LocalStorePsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BookStore/CreateChain',
            bookstore__pb2.CreateChainRequest.SerializeToString,
            bookstore__pb2.CreateChainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BookStore/RemoveChain',
            bookstore__pb2.CreateChainRequest.SerializeToString,
            bookstore__pb2.CreateChainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BookStore/ListChain',
            bookstore__pb2.ListChainRequest.SerializeToString,
            bookstore__pb2.ListChainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BookStore/WriteOperation',
            bookstore__pb2.WriteOperationRequest.SerializeToString,
            bookstore__pb2.WriteOperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BookStore/ListBooks',
            bookstore__pb2.ListOperationRequest.SerializeToString,
            bookstore__pb2.ListOperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BookStore/ReadOperation',
            bookstore__pb2.ReadOperationRequest.SerializeToString,
            bookstore__pb2.ReadOperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetTimeout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BookStore/SetTimeout',
            bookstore__pb2.SetTimeoutRequest.SerializeToString,
            bookstore__pb2.SetTimeoutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DataStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BookStore/DataStatus',
            bookstore__pb2.DataStatusRequest.SerializeToString,
            bookstore__pb2.DataStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveHead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BookStore/RemoveHead',
            bookstore__pb2.ListChainRequest.SerializeToString,
            bookstore__pb2.ListChainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RestoreHead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BookStore/RestoreHead',
            bookstore__pb2.RestoreHeadRequest.SerializeToString,
            bookstore__pb2.RestoreHeadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLocalDataStores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BookStore/GetLocalDataStores',
            bookstore__pb2.GetLocalDataStoresRequest.SerializeToString,
            bookstore__pb2.GetLocalDataStoresResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BookStore/SetChain',
            bookstore__pb2.SetChainRequest.SerializeToString,
            bookstore__pb2.SetChainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
