# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import bookstore_pb2 as bookstore__pb2


class BookStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LocalStorePs = channel.unary_unary(
                '/bookstore.BookStore/LocalStorePs',
                request_serializer=bookstore__pb2.LocalStorePsRequest.SerializeToString,
                response_deserializer=bookstore__pb2.LocalStorePsResponse.FromString,
                )
        self.CreateChain = channel.unary_unary(
                '/bookstore.BookStore/CreateChain',
                request_serializer=bookstore__pb2.CreateChainRequest.SerializeToString,
                response_deserializer=bookstore__pb2.CreateChainResponse.FromString,
                )
        self.ListChain = channel.unary_unary(
                '/bookstore.BookStore/ListChain',
                request_serializer=bookstore__pb2.ListChainRequest.SerializeToString,
                response_deserializer=bookstore__pb2.ListChainResponse.FromString,
                )
        self.WriteOperation = channel.unary_unary(
                '/bookstore.BookStore/WriteOperation',
                request_serializer=bookstore__pb2.WriteOperationRequest.SerializeToString,
                response_deserializer=bookstore__pb2.WriteOperationResponse.FromString,
                )
        self.ListBooks = channel.unary_unary(
                '/bookstore.BookStore/ListBooks',
                request_serializer=bookstore__pb2.ListBooksRequest.SerializeToString,
                response_deserializer=bookstore__pb2.ListBooksResponse.FromString,
                )
        self.ReadOperation = channel.unary_unary(
                '/bookstore.BookStore/ReadOperation',
                request_serializer=bookstore__pb2.ReadOperationRequest.SerializeToString,
                response_deserializer=bookstore__pb2.ReadOperationResponse.FromString,
                )
        self.SetTimeout = channel.unary_unary(
                '/bookstore.BookStore/SetTimeout',
                request_serializer=bookstore__pb2.SetTimeoutRequest.SerializeToString,
                response_deserializer=bookstore__pb2.SetTimeoutResponse.FromString,
                )
        self.DataStatus = channel.unary_unary(
                '/bookstore.BookStore/DataStatus',
                request_serializer=bookstore__pb2.DataStatusRequest.SerializeToString,
                response_deserializer=bookstore__pb2.DataStatusResponse.FromString,
                )
        self.RemoveHead = channel.unary_unary(
                '/bookstore.BookStore/RemoveHead',
                request_serializer=bookstore__pb2.RemoveHeadRequest.SerializeToString,
                response_deserializer=bookstore__pb2.RemoveHeadResponse.FromString,
                )
        self.RestoreHead = channel.unary_unary(
                '/bookstore.BookStore/RestoreHead',
                request_serializer=bookstore__pb2.RestoreHeadRequest.SerializeToString,
                response_deserializer=bookstore__pb2.RestoreHeadResponse.FromString,
                )


class BookStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LocalStorePs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateChain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTimeout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DataStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveHead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreHead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LocalStorePs': grpc.unary_unary_rpc_method_handler(
                    servicer.LocalStorePs,
                    request_deserializer=bookstore__pb2.LocalStorePsRequest.FromString,
                    response_serializer=bookstore__pb2.LocalStorePsResponse.SerializeToString,
            ),
            'CreateChain': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChain,
                    request_deserializer=bookstore__pb2.CreateChainRequest.FromString,
                    response_serializer=bookstore__pb2.CreateChainResponse.SerializeToString,
            ),
            'ListChain': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChain,
                    request_deserializer=bookstore__pb2.ListChainRequest.FromString,
                    response_serializer=bookstore__pb2.ListChainResponse.SerializeToString,
            ),
            'WriteOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteOperation,
                    request_deserializer=bookstore__pb2.WriteOperationRequest.FromString,
                    response_serializer=bookstore__pb2.WriteOperationResponse.SerializeToString,
            ),
            'ListBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBooks,
                    request_deserializer=bookstore__pb2.ListBooksRequest.FromString,
                    response_serializer=bookstore__pb2.ListBooksResponse.SerializeToString,
            ),
            'ReadOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadOperation,
                    request_deserializer=bookstore__pb2.ReadOperationRequest.FromString,
                    response_serializer=bookstore__pb2.ReadOperationResponse.SerializeToString,
            ),
            'SetTimeout': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTimeout,
                    request_deserializer=bookstore__pb2.SetTimeoutRequest.FromString,
                    response_serializer=bookstore__pb2.SetTimeoutResponse.SerializeToString,
            ),
            'DataStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.DataStatus,
                    request_deserializer=bookstore__pb2.DataStatusRequest.FromString,
                    response_serializer=bookstore__pb2.DataStatusResponse.SerializeToString,
            ),
            'RemoveHead': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveHead,
                    request_deserializer=bookstore__pb2.RemoveHeadRequest.FromString,
                    response_serializer=bookstore__pb2.RemoveHeadResponse.SerializeToString,
            ),
            'RestoreHead': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreHead,
                    request_deserializer=bookstore__pb2.RestoreHeadRequest.FromString,
                    response_serializer=bookstore__pb2.RestoreHeadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bookstore.BookStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BookStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LocalStorePs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BookStore/LocalStorePs',
            bookstore__pb2.LocalStorePsRequest.SerializeToString,
            bookstore__pb2.LocalStorePsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BookStore/CreateChain',
            bookstore__pb2.CreateChainRequest.SerializeToString,
            bookstore__pb2.CreateChainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BookStore/ListChain',
            bookstore__pb2.ListChainRequest.SerializeToString,
            bookstore__pb2.ListChainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BookStore/WriteOperation',
            bookstore__pb2.WriteOperationRequest.SerializeToString,
            bookstore__pb2.WriteOperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BookStore/ListBooks',
            bookstore__pb2.ListBooksRequest.SerializeToString,
            bookstore__pb2.ListBooksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BookStore/ReadOperation',
            bookstore__pb2.ReadOperationRequest.SerializeToString,
            bookstore__pb2.ReadOperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetTimeout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BookStore/SetTimeout',
            bookstore__pb2.SetTimeoutRequest.SerializeToString,
            bookstore__pb2.SetTimeoutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DataStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BookStore/DataStatus',
            bookstore__pb2.DataStatusRequest.SerializeToString,
            bookstore__pb2.DataStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveHead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BookStore/RemoveHead',
            bookstore__pb2.RemoveHeadRequest.SerializeToString,
            bookstore__pb2.RemoveHeadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RestoreHead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BookStore/RestoreHead',
            bookstore__pb2.RestoreHeadRequest.SerializeToString,
            bookstore__pb2.RestoreHeadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
